services:
  elice-streamlit:
    container_name: elice-streamlit
    image: elice-streamlit
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8503:8503

  elice-qdrant:
    container_name: elice-qdrant
    image: qdrant/qdrant:v1.7.3
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./.docker/data/qdrant_storage:/qdrant/storage

  elice-redis:
    container_name: elice-redis
    image: redis:6.2.5
    ports:
      - 6379:6379
    volumes:
      - ./.docker/data/redis_storage:/data
